runtime: python38  # or another runtime suitable for your application

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /assets
  static_dir: assets

- url: /images
  static_dir: images

- url: /(.*\.(html|css|js|png|jpg|gif|webp|svg))
  static_files: \1
  upload: (.*\.(html|css|js|png|jpg|gif|webp|svg))
